### ISSUE TITLE
Segmentation fault on Linux after clicking an archer or warrior

### ISSUE THREAD

**Issue by przem360** [bosorioo/rts-game-console#3]
First let me say that your game is very cool, I really enjoy playing it :)

Now, a bug...
This is not critical but an unexpected behavior fur sure.
I probably should not click the archer or warrior, but I've tried.
So whenever I click archer `a` or warrior `w` game crashes with segmentation fault.

GDB output (identical for SIGSEGV after clicking archer and warrior):  
```
Program received signal SIGSEGV, Segmentation fault.
0x000055555555ad29 in Unit_GetOwner (u=u@entry=0x69) at src/unit.c:123
123	    return u ? u->owner : NULL;
(gdb) backtrace
#0  0x000055555555ad29 in Unit_GetOwner (u=u@entry=0x69) at src/unit.c:123
#1  0x000055555555778e in Display_DrawMap (d=d@entry=0x555555572300, 
    m=m@entry=0x555555572620, p=p@entry=0x555555575f00, x=<optimized out>, 
    x@entry=7, y=y@entry=3, xLimit=<optimized out>, yLimit=<optimized out>, 
    cameraX=0, cameraY=0) at src/display.c:355
#2  0x000055555555c99b in GamePlay_onRender (s=<optimized out>)
    at src/screens/game_play.c:111
#3  0x00005555555567a9 in main (argc=<optimized out>, args=<optimized out>)
    at src/main.c:74
(gdb) 
```

**Comment by bosorioo** [comment]
Yes, the code is missing a lot of checks that end up crashing when some characters are printed outside the bounds of the terminal. This ends up happening a lot if the terminal window isn't wide/long enough.
I made some changes to prevent some out-of-bounds writes, but if the terminal window isn't big enough, some information won't be shown in the screen.

Regardless, the crash should be fixed by now.

**Comment by przem360** [comment]
It works!
